app:
  image: node:4-onbuild
  volumes:
  - ./:/app
  - node_modules:/app/node_modules
  working_dir: /app
  command: bash -c "npm install && node server.js"
  links:
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/app
  - VIRTUAL_HOST=react-starter.docker
  expose:
  - 3000
mongo:
  image: mongo
